### ISSUE TITLE
fix: checklist of fixes

### ISSUE THREAD

**Issue by leivans** [open-social-care/frontend#45]
- [x] Invalid date in subjects list page (last form answer date).
- [x] Missing "{{subject_ref}}" in create subject page.
- [x] Add message when form answers list is empty.
- [x] Add message when form template list is empty on create form answer page.
- [x] Redirect incorrect after create form answer.
