### ISSUE TITLE
fix: checklist of fixes

### ISSUE THREAD

**Issue by leivans** [open-social-care/frontend#48]
- [x] birthdate on edit subject page
- [x] edit subject ref on oranization
- [x] "missing subject_ref" occurrences
